env:
  matrix:
    # Do not change this order
    - DOCS="true"
    - WEBSITE="true"
  global:
    secure: "5ElZf1fy+lG3qaL0fsUziva0Z2GHRg3xVVh1vssBXSlWifvACz2XU0VA0CE3URuLeBnwQLUYs+z11T2YmXTg5BoJI2wYDBaETXqk4Sb5qK6ecv2KIquvREavHPFoVdmHYoeYhDcHZufYgQn/Dx1E79xep4A+R/T8SdtDk2OxPWw="

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
  - bash ~/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
  - conda update -yq conda
  - conda install -yq conda-build
  - conda info -a
  - conda config --append channels conda-forge
  - conda config --append channels asmeurer

  - if [[ "${DOCS}" = "true" ]]; then
      conda install pycrypto;
      conda create -q -n build-environment -c asmeurer conda-docs-deps doctr;
      cd docs;
    fi
  - if [[ "${WEBSITE}" = "true" ]]; then
      conda create -q -n build-environment -c asmeurer sphinxjp.themes.basicstrap cloud_sptheme doctr;
      cd web;
    fi
  - source activate build-environment

script:
  - set -e # Fail if any of the below errors
  - set -x # Show the commands that are run
  - make html-errors
  - cd ..
  - if [[ "${DOCS}" = "true" ]]; then
      doctr deploy --built-docs docs/build/html --gh-pages-docs docs;
    fi
  - if [[ "${WEBSITE}" = "true" ]]; then
      doctr deploy --built-docs web/build/html --gh-pages-docs .;
    fi
notifications:
  flowdock: ef3821a08a791106512ccfc04c92eccb

sudo: false
